spring:
  datasource:
    name: ${DB_NAME}
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://${DB_URL}:3306/ecom?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC'
    username: '${DB_USER}'
    max-active: 10
    max-idle: 5
    min-idle: 2
    initial-size: 2
    remove-abandoned: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
  main:
    log-startup-info: true
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 5000
logging:
  level:
    root: info
    sql: info
    web: info
