spring:
  datasource:
    name: 'ecom'
  jpa:
    show-sql: true
    database: H2
  h2:
    console:
      enabled: true
      path: '/h2-console'
logging:
  level:
    root: info
    sql: info
    web: debug
