name: heroku-deploy
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_ECOM }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}


  custom-deploy:
    needs: heroku-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
              machine api.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API
              machine git.heroku.com
                login $HEROKU_EMAIL
                password $HEROKU_API
          EOF
        env:
          HEROKU_API: ${{ secrets.HEROKU_API }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME_ECOM
        env:
          HEROKU_APP_NAME_ECOM: ${{ secrets.HEROKU_APP_NAME_ECOM }}
      - name: Push to heroku
        run: git push heroku master
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}