name: Maven Build
on:
  pull_request:
    paths:
      - '**.java'
      - '**.xml'
      - '**.properties'
    branches:
      - master
    push:
      paths:
        - '**.java'
        - '**.xml'
        - '**.properties'
      branches:
        - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout projet
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven
        run: mvn -B package --file pom.xml
#- name: action-maven
#  uses: comchangs/action-maven@v0.4-beta
#
#workflow "build test" {
#  resolves = ["comchangs/action-maven"]
#  on = "push"
#}
#
#action "comchangs/action-maven" {
#  uses = "comchangs/action-maven@master"
#  args = "clean compile test"
#}


